name: Run Super-Linter

on:
  workflow_dispatch:  # This allows manual triggering from the Actions tab

jobs:
  lint-code:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.4.0 # x-release-please-version
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
